### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by geggleto** [acfo/session#1]
Hello

In your readme
```php
$app->add(
	new \Acfo\Session\Middleware\Slim3\SessionMiddleware(
		$container->get(\Acfo\Session\Session::class)
	)
);
```

The new object creation should be handled by pimple; so then you would simply say
`$app->add(\Acfo\Session\Middleware\Slim3\SessionMiddleware::class);`

I'm not particularly fond of the naming conventions, I would have done something like SessionInterface and Session (for the implementation).

**Comment by acfo** [comment]
Thanks! I've changed the readme to include your suggestions. 

Concerning adding an Interface-postfix to the name of an interface: I've decided to follow Uncle Bobs suggestion for naming interfaces.
